core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django import views
from django.contrib import admin
from django.urls import path, include  # add this


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),             
    path('accounts/', include('django.contrib.auth.urls')),  
  #  path('register/', views.register, name='register'),    
   
    path('', include('apps.registro.urls')),  
    path('marketplace/', include('apps.marketplace.urls')),  
]

apps/registro/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.validators import EmailValidator
from django.core.validators import RegexValidator


# Gerenciador para criar usuários personalizados
class UsuarioManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("O email é obrigatório")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, password, **extra_fields)

# Regex para validar números de telefone no formato (XX) XXXX-XXXX ou (XX) XXXXX-XXXX
telefone_validator = RegexValidator(
    regex=r'^\(\d{2}\) \d{4,5}-\d{4}$',
    message="O número de telefone deve estar no formato (XX) XXXX-XXXX ou (XX) XXXXX-XXXX."
)

# Modelo do usuário personalizado
class Usuario(AbstractUser):
    email = models.EmailField(validators=[EmailValidator()] ,unique=True)
    telefone = models.CharField(
        max_length=15, 
        validators=[telefone_validator],
        blank=True, 
        null=True
    )
    is_vendedor = models.BooleanField(default=False)
    foto_base64 = models.TextField(blank=True, null=True)
    # Campos não usados pelo AbstractUser
    username = None

    # Campo único para autenticação
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UsuarioManager()

    def __str__(self):
        return self.email


class Vendedor(models.Model):
    usuario = models.OneToOneField(Usuario, on_delete=models.CASCADE, related_name='vendedor')
    localizacao = models.CharField(max_length=255, blank=True, null=True)
    telefone = models.CharField(max_length=15, blank=True, null=True)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.usuario.email


from django.db import models

class Produto(models.Model):
    vendedor = models.ForeignKey(Vendedor, on_delete=models.CASCADE, related_name='produtos')
    nome = models.CharField(max_length=100)
    descricao = models.TextField()
    preco = models.DecimalField(max_digits=10, decimal_places=2, validators=[
        MinValueValidator(0.10),  # O preço não pode ser menor ou igual a 0.10
        MaxValueValidator(100)   # O preço máximo será 100
    ])
    disponibilidade = models.BooleanField(default=True)
    num_vendas = models.PositiveIntegerField(default=0)  
    num_produtos = models.IntegerField(validators=[MinValueValidator(0)])

    imagem_base64 = models.TextField(blank=True, null=True)  # Armazena a versão Base64 da imagem

    def __str__(self):
        return self.nome


class Pedido(models.Model):
    comprador = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name='pedidos')
    vendedor = models.ForeignKey(Vendedor, on_delete=models.CASCADE, related_name='pedidos')
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    preco_total = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=50, choices=[('pendente', 'Pendente'), ('concluido', 'Concluído')])
    atualizado_em = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Pedido {self.id} - {self.comprador.email} para {self.vendedor.usuario.email}"

class Avaliacao(models.Model):
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE, related_name='avaliacoes')
    avaliador = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name='avaliacoes')
    nota = models.PositiveIntegerField()
    comentario = models.TextField(blank=True, null=True)
    data_avaliacao = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('produto', 'avaliador')  # Garante que um usuário avalie apenas uma vez um produto

    def __str__(self):
        return f"Avaliação de {self.avaliador.email} no produto {self.produto.nome}"


class Chat(models.Model):
    comprador = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name="comprador_chats")
    vendedor = models.ForeignKey(Vendedor, on_delete=models.CASCADE, related_name="vendedor_chats")  # Altere para Vendedor
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE, related_name="chats")
    mensagem = models.TextField()
    data_horario = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        
        return f"Chat: {self.comprador} -> {self.vendedor} ({self.produto.nome})"


class Notificacao(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name='notificacoes')
    mensagem = models.TextField()
    enviado_em = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Notificação para {self.usuario.email}"


class Pagamento(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE, related_name="pagamentos")
    status = models.CharField(max_length=50, choices=[("pendente", "Pendente"), ("aprovado", "Aprovado"), ("recusado", "Recusado")])
    metodo = models.CharField(max_length=50, default="Mercado Pago")
    id_transacao = models.CharField(max_length=100, unique=True)
    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Pagamento {self.id_transacao} - {self.status}"

apps/templates/produto/cadastro_produto.html
{% extends "marketplace/base.html" %}

{% block content %}
  <div class="container mt-5">
    <div class="card shadow-sm" >
      <div class="card-header  text-white text-center" style="background-color:#bb2d3b" >
        <h1 class="h5 mb-0">Cadastrar Produto</h1>
      </div>
      <div class="card-body">
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}

          <!-- Nome do Produto -->
          <div class="row mb-3 align-items-center">
            <div class="col-md-3">
              <label for="id_nome" class="form-label">Nome do Produto</label>
            </div>
            <div class="col-md-9">
              <input type="text" id="id_nome" name="nome" class="form-control">
            </div>
          </div>

          <!-- Descrição -->
          <div class="row mb-3 align-items-center">
            <div class="col-md-3">
              <label for="id_descricao" class="form-label">Descrição</label>
            </div>
            <div class="col-md-9">
              <textarea id="id_descricao" name="descricao" class="form-control" rows="3"></textarea>
            </div>
          </div>

          <!-- Preço -->
          <div class="row mb-3 align-items-center">
            <div class="col-md-3">
              <label for="id_preco" class="form-label">Preço</label>
            </div>
            <div class="col-md-9">
              <input type="text" id="id_preco" name="preco" class="form-control">
            </div>
          </div>

          <!-- Disponibilidade -->
          <div class="row mb-3 align-items-center">
            <div class="col-md-3">
              <label for="id_disponibilidade" class="form-label">Disponibilidade</label>
            </div>
            <div class="col-md-9">
              <div class="form-check form-switch">
                <input type="checkbox" id="id_disponibilidade" name="disponibilidade" class="form-check-input">
              
              </div>
            </div>
          </div>
          <!-- N mero de Produtos -->
          <div class="row mb-3 align-items-center">
            <div class="col-md-3">
              <label for="id_num_produtos" class="form-label">Número de Produtos</label>
            </div>
            <div class="col-md-9">
              <input type="number" id="id_num_produtos" name="num_produtos" class="form-control" min="1" value="1">
            </div>
          </div>
          <!-- Foto do Produto -->
          <div class="row mb-3 align-items-center">
            <div class="col-md-3">
              <label for="photoUpload" class="form-label">Foto do Produto</label>
            </div>
            <div class="col-md-9">
              <input 
                type="file" 
                id="photoUpload" 
                name="foto" 
                accept="image/*" 
                class="form-control" 
                onchange="previewPhoto(event)">
              <div class="mt-3">
                <img id="photoPreview" src="#" alt="Preview da Foto" class="img-thumbnail d-none" style="max-width: 200px;">
              </div>
            </div>
          </div>

          <!-- Botão de Envio -->
          <div class="d-grid">
            <button type="submit" class="btn btn-primary btn-block">Cadastrar Produto</button>
          </div>
        </form>
      </div>
    </div>
  </div>

  <script>
    // Função para pré-visualizar a imagem
    function previewPhoto(event) {
      const photoPreview = document.getElementById('photoPreview');
      const file = event.target.files[0];
      if (file) {
        const reader = new FileReader();
        reader.onload = function (e) {
          photoPreview.src = e.target.result;
          photoPreview.classList.remove('d-none');
        };
        reader.readAsDataURL(file);
      }
    }
  </script>
{% endblock %}

apps/templates/produto/meus_produtos.html
{% extends 'marketplace/base.html' %}

{% block content %}
<div class="container py-4">
    <h1 class="text-center mb-4">Meus Produtos</h1>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="table-responsive">
            <table class="table table-bordered">
                <thead class="table-light">
                    <tr>
                        <th class="text-center">Imagem</th>
                        <th class="text-center">Nome</th>
                        <th class="text-center">Descrição</th>
                        <th class="text-center" style="width: 80px;">Disponibilidade</th>
                        <th class="text-center" style="width: 180px;">Ações</th>
                    </tr>
                </thead>
                <tbody>
                    {% for produto in produtos %}
                    <tr>
                        <td class="text-center">
                            {% if produto.imagem_base64 %}
                            <img src="data:image/png;base64,{{ produto.imagem_base64 }}" alt="Imagem do produto" class="img-thumbnail" style="width: 100px; height: 100px; object-fit: cover;" />
                            {% else %}
                            <span class="text-muted">Sem imagem</span>
                            {% endif %}
                        </td>
                        <td class="text-center"><strong>{{ produto.nome }}</strong></td>
                        <td class="text-justify">{{ produto.descricao }}</td>
                        <td class="text-center">
                            <!-- Slider button maior -->
                            <div class="form-check form-switch d-inline-block">
                                <input 
                                    class="form-check-input" 
                                    type="checkbox" 
                                    role="switch" 
                                    id="disponivel_{{ produto.id }}" 
                                    name="produto_{{ produto.id }}" 
                                    value="True" 
                                    style="width: 3rem; height: 1.5rem;" 
                                    {% if produto.disponibilidade %} checked {% endif %}
                                >
                            </div>
                        </td>
                        <td class="text-center">
                            <!-- Botão Editar Produto -->
                            <a href="{% url 'editar_produto' produto.id %}" class="btn btn-primary btn-sm">
                                Editar
                            </a>
                            <!-- Botão Deletar Produto -->
                            <form action="{% url 'deletar_produto' produto.id %}" method="POST" style="display: inline;">
                              {% csrf_token %}
                              <button type="submit" class="btn btn-danger btn-sm"
                                  onclick="return confirm('Tem certeza que deseja deletar este produto? {{ produto.nome }} (ID: {{ produto.id }})')">
                                  Deletar
                              </button>
                          </form>
                          
                          
                          
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="text-center mt-3">
            <button type="submit" class="btn btn-success btn-lg">Atualizar Disponibilidade</button>
        </div>
    </form>
</div>
{% endblock %}

apps/templates/produto/minhas_avaliacoes.html
{% extends "marketplace/base.html" %}

{% block title %}Minhas Avaliações{% endblock %}

{% block content %}
<div class="container mt-5 pt-5">
    <h2 class="mb-4 text-center text-primary">Minhas Avaliações</h2>
    
    {% if avaliacoes %}
        <div class="list-group">
            {% for avaliacao in avaliacoes %}
                <div class="list-group-item">
                    <div class="d-flex justify-content-between align-items-center">
                        <h5 class="mb-1 text-danger">{{ avaliacao.produto.nome }}</h5>
                        <small class="text-muted">Nota: <strong>{{ avaliacao.nota }}</strong></small>
                    </div>
                    <p class="mb-1">{{ avaliacao.comentario }}</p>
                    <small class="text-muted">Avaliado em: {{ avaliacao.data_avaliacao|date:"d/m/Y H:i" }}</small>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="alert alert-warning text-center mt-4">
            <p>Você ainda não fez nenhuma avaliação.</p>
        </div>
    {% endif %}
</div>
{% endblock %}

apps/templates/produto/produto_editar.html
{% extends "marketplace/base.html" %}

{% block content %}
  <div class="container mt-5">
    <div class="card shadow-sm">
      <div class="card-header bg-primary text-white text-center">
        <h1 class="h5 mb-0">Editar Produto</h1>
      </div>
      <div class="card-body">
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}

          <!-- Nome do Produto -->
          <div class="row mb-3 align-items-center">
            <div class="col-md-3">
              <label for="id_nome" class="form-label">Nome do Produto</label>
            </div>
            <div class="col-md-9">
              <input type="text" id="id_nome" name="nome" class="form-control" value="{{ produto.nome }}">
            </div>
          </div>

          <!-- Descrição -->
          <div class="row mb-3 align-items-center">
            <div class="col-md-3">
              <label for="id_descricao" class="form-label">Descrição</label>
            </div>
            <div class="col-md-9">
              <textarea id="id_descricao" name="descricao" class="form-control" rows="3">{{ produto.descricao }}</textarea>
            </div>
          </div>

          <!-- Preço -->
          <div class="row mb-3 align-items-center">
            <div class="col-md-3">
              <label for="id_preco" class="form-label">Preço</label>
            </div>
            <div class="col-md-9">
              <input type="text" id="id_preco" name="preco" class="form-control" value="{{ produto.preco }}">
            </div>
          </div>

          <!-- Disponibilidade -->
          <div class="row mb-3 align-items-center">
            <div class="col-md-3">
              <label for="id_disponibilidade" class="form-label">Disponibilidade</label>
            </div>
            <div class="col-md-9">
              <div class="form-check form-switch">
                <input 
                  type="checkbox" 
                  id="id_disponibilidade" 
                  name="disponibilidade" 
                  class="form-check-input" 
                  {% if produto.disponibilidade %} checked {% endif %}
                >
              </div>
            </div>
          </div>

          <!-- N mero de Produtos -->
          <div class="row mb-3 align-items-center">
            <div class="col-md-3">
              <label for="id_num_produtos" class="form-label">Número de Produtos</label>
            </div>
            <div class="col-md-9">
              <input type="number" id="id_num_produtos" name="num_produtos" class="form-control" value="{{ produto.num_produtos }}">
            </div>
          </div>

          <!-- Foto do Produto -->
          <div class="row mb-3 align-items-center">
            <div class="col-md-3">
              <label for="photoUpload" class="form-label">Foto do Produto</label>
            </div>
            <div class="col-md-9">
              <input 
                type="file" 
                id="photoUpload" 
                name="foto" 
                accept="image/*" 
                class="form-control" 
                onchange="previewPhoto(event)">
              <div class="mt-3">
                <!-- Preview Inicial com Imagem Base64 -->
                <img 
                  id="photoPreview" 
                  src="{% if produto.imagem_base64 %}data:image/png;base64,{{ produto.imagem_base64 }}{% else %}# {% endif %}" 
                  alt="Preview da Imagem" 
                  class="img-thumbnail {% if not produto.imagem_base64 %}d-none{% endif %}" 
                  style="max-width: 200px;">
              </div>
            </div>
          </div>

          <!-- Botões -->
          <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <button type="submit" class="btn btn-success">Salvar Alterações</button>
            <a href="{% url 'marketplace' %}" class="btn btn-secondary">Cancelar</a>
          </div>
        </form>
      </div>
    </div>
  </div>

  <script>
    // Função para pré-visualizar a imagem
    function previewPhoto(event) {
        const photoPreview = document.getElementById('photoPreview');
        const file = event.target.files[0];

        if (file) {
            const reader = new FileReader();
            reader.onload = function (e) {
                photoPreview.src = e.target.result; // Atualiza o preview com a nova imagem
                photoPreview.classList.remove('d-none'); // Mostra o preview caso estivesse oculto
            };
            reader.readAsDataURL(file);
        }
    }
  </script>
{% endblock %}